CREATE TABLE CUSTOMER_ADDRESS_WITH_COMPRESSION
	LIKE CUSTOMER_ADDRESS_WITHOUT_COMPRESSION
	NOT LOGGED INITIALLY;

INSERT INTO CUSTOMER_ADDRESS_WITH_COMPRESSION
	SELECT * FROM CUSTOMER_ADDRESS_WITHOUT_COMPRESSION;

ALTER TABLE CUSTOMER_ADDRESS_WITH_COMPRESSION
	COMPRESS YES;

CALL ADMIN_CMD('REORG TABLE ?SCHEMA?.CUSTOMER_ADDRESS_WITH_COMPRESSION');

CALL ADMIN_CMD('RUNSTATS ON TABLE ?SCHEMA?.CUSTOMER_ADDRESS_WITH_COMPRESSION')
