CREATE TABLE CUSTOMER_ADDRESS_WITH_AUTO_COMPRESSION
	LIKE CUSTOMER_ADDRESS_WITHOUT_COMPRESSION 
	COMPRESS YES 
	NOT LOGGED INITIALLY;

INSERT INTO CUSTOMER_ADDRESS_WITH_AUTO_COMPRESSION
	SELECT * FROM CUSTOMER_ADDRESS_WITH_COMPRESSION;

CALL ADMIN_CMD('RUNSTATS ON TABLE ?SCHEMA?.CUSTOMER_ADDRESS_WITH_AUTO_COMPRESSION');