ALTER SEQUENCE EMPNO RESTART WITH 100;

VALUES NEXTVAL FOR DEPTNO;

INSERT INTO SEQ_EMPLOYEE_SECOND VALUES
  (EMPNO.NEXTVAL, DEPTNO.CURRVAL, 'George'),
  (EMPNO.NEXTVAL, DEPTNO.CURRVAL, 'Paul'),
  (EMPNO.NEXTVAL, DEPTNO.CURRVAL, 'Kevin');
  
SELECT * FROM SEQ_EMPLOYEE_SECOND;