-- Get selective information from MON_GET_CONNECTION table function
SELECT APPLICATION_HANDLE, 
       APPLICATION_NAME,
	   TOTAL_CPU_TIME, 
	   TOTAL_ACT_TIME, 
	   ACT_COMPLETED_TOTAL, 
	   TOTAL_WAIT_TIME, 
	   CLIENT_IDLE_WAIT_TIME
	FROM TABLE(MON_GET_CONNECTION(NULL, -1)) as t;