select XMLELEMENT( NAME "database", XMLATTRIBUTES(
	DB_NAME,DB_STATUS,DB_CONN_TIME,LAST_BACKUP,APPLS_CUR_CONS,CONNECTIONS_TOP,DEADLOCKS,LOCK_ESCALS,LOCK_LIST_IN_USE AS LOCK_LIST_IN_USE,LOCK_WAITS AS LOCK_WAITS,DIRECT_READS AS DIRECT_READS,DIRECT_READ_TIME AS DIRECT_READ_TIME,DIRECT_WRITES AS DIRECT_WRITES,DIRECT_WRITE_TIME AS DIRECT_WRITE_TIME,LOG_READS AS LOG_READS,LOG_WRITES AS LOG_WRITES,SORT_HEAP_ALLOCATED AS SORT_HEAP_ALLOCATED,SORT_OVERFLOWS AS SORT_OVERFLOWS,SORT_SHRHEAP_ALLOCATED AS SORT_SHRHEAP_ALLOCATED,TOTAL_SORTS AS TOTAL_SORTS,POOL_ASYNC_DATA_READS AS POOL_ASYNC_DATA_READS,POOL_ASYNC_DATA_WRITES AS POOL_ASYNC_DATA_WRITES,POOL_ASYNC_INDEX_READS AS POOL_ASYNC_INDEX_READS,POOL_ASYNC_INDEX_WRITES AS POOL_ASYNC_INDEX_WRITES,POOL_DATA_L_READS AS POOL_DATA_L_READS,POOL_DATA_P_READS AS POOL_DATA_P_READS,POOL_DATA_WRITES AS POOL_DATA_WRITES,POOL_INDEX_L_READS AS POOL_INDEX_L_READS,POOL_INDEX_P_READS AS POOL_INDEX_P_READS,POOL_INDEX_WRITES AS POOL_INDEX_WRITES,POOL_READ_TIME,POOL_TEMP_DATA_L_READS,POOL_TEMP_DATA_P_READS,POOL_TEMP_INDEX_L_READS,POOL_TEMP_INDEX_P_READS,POOL_WRITE_TIME,SNAPSHOT_TIMESTAMP
	)
	,(select XMLELEMENT(NAME "schemas"
				,XMLAGG(XMLELEMENT(NAME "schema"
						,XMLATTRIBUTES(SCHEMANAME,OWNER,DEFINER,CREATE_TIME,REMARKS)
						) order by SCHEMANAME
					))
		from SYSCAT.SCHEMATA s
		)
	,(select XMLELEMENT(NAME "bufferpools"
				,XMLAGG(XMLELEMENT(NAME "bufferpool"
						,XMLATTRIBUTES(BPNAME,BUFFERPOOLID,DBPGNAME,NPAGES,PAGESIZE,ESTORE,NUMBLOCKPAGES,BLOCKSIZE,NGNAME)
						) order by BPNAME
					))
		from SYSCAT.BUFFERPOOLS b
		)
	,(select XMLELEMENT(NAME "tablespaces"
				,XMLAGG(XMLELEMENT(NAME "tablespace"
						,XMLATTRIBUTES(TBSPACE,OWNER,CREATE_TIME,TBSPACEID,TBSPACETYPE,DATATYPE,EXTENTSIZE,PREFETCHSIZE,OVERHEAD,TRANSFERRATE,PAGESIZE,DBPGNAME,BUFFERPOOLID,DROP_RECOVERY,NGNAME,DEFINER,REMARKS)
						) order by TBSPACE
					))
		from SYSCAT.TABLESPACES S
		)
	) 
from SYSIBMADM.SNAPDB as d