select XMLELEMENT( NAME "database", XMLATTRIBUTES(
	DB_NAME
	)
	,(select XMLELEMENT(NAME "schemas"
				,XMLAGG(XMLELEMENT(NAME "schema"
						,XMLATTRIBUTES(SCHEMANAME,OWNER,DEFINER,CREATE_TIME,REMARKS)
						) order by SCHEMANAME
					))
		from SYSCAT.SCHEMATA s
		)
	,(select XMLELEMENT(NAME "bufferpools"
				,XMLAGG(XMLELEMENT(NAME "bufferpool"
						,XMLATTRIBUTES(BPNAME,BUFFERPOOLID,DBPGNAME,NPAGES,PAGESIZE,ESTORE,NUMBLOCKPAGES,BLOCKSIZE,NGNAME)
						) order by BPNAME
					))
		from SYSCAT.BUFFERPOOLS b
		)
	,(select XMLELEMENT(NAME "tablespaces"
				,XMLAGG(XMLELEMENT(NAME "tablespace"
						,XMLATTRIBUTES(TBSPACE,OWNER,CREATE_TIME,TBSPACEID,TBSPACETYPE,DATATYPE,EXTENTSIZE,PREFETCHSIZE,OVERHEAD,TRANSFERRATE,PAGESIZE,DBPGNAME,BUFFERPOOLID,DROP_RECOVERY,NGNAME,DEFINER,REMARKS)
						) order by TBSPACE
					))
		from SYSCAT.TABLESPACES S
		)
	) 
from (values('database')) as d(DB_NAME)