select XMLELEMENT( NAME "functions"
	,	XMLAGG(XMLELEMENT(NAME "function"
				,XMLATTRIBUTES(FUNCSCHEMA,FUNCNAME,SPECIFICNAME,DEFINER,FUNCID,RETURN_TYPE,ORIGIN,METHOD,EFFECT,PARM_COUNT,PARM_SIGNATURE)
				) order by FUNCSCHEMA,FUNCNAME
			)
		)
from syscat.functions
