select XMLELEMENT( NAME "procedures"
	,	XMLAGG(XMLELEMENT(NAME "procedure"
				,XMLATTRIBUTES(DEFINER,LANGUAGE,ORIGIN,PARM_COUNT,PARM_SIGNATURE,PARM_STYLE,PROCEDURE_ID,PROCNAME,PROCSCHEMA,PROGRAM_TYPE,SPECIFICNAME,VALID)
				) order by PROCSCHEMA,PROCNAME
			)
		)
from syscat.PROCEDURES  




