select XMLELEMENT( NAME "sequences"
	,	XMLAGG(XMLELEMENT(NAME "sequence"
				,XMLATTRIBUTES(SEQSCHEMA,SEQNAME 
					,DEFINER,DEFINERTYPE,OWNER,OWNERTYPE,SEQID,SEQTYPE,INCREMENT,START,MAXVALUE,MINVALUE,NEXTCACHEFIRSTVALUE,CYCLE,CACHE,ORDER,DATATYPEID,SOURCETYPEID AS SOURCETYPEID,CREATE_TIME,ALTER_TIME,PRECISION,ORIGIN,REMARKS
				)
				) order by SEQSCHEMA,SEQNAME
			)
		)
from syscat.SEQUENCES
