select XMLELEMENT( NAME "table"
	,XMLATTRIBUTES(OWNER,TABLE_NAME,TABLESPACE_NAME)
	,XMLELEMENT(NAME "columns"
		,(	select XMLAGG(
				XMLELEMENT(NAME "column"
					,XMLATTRIBUTES(COLUMN_NAME,DATA_TYPE,DATA_TYPE_MOD,DATA_TYPE_OWNER
							,CAST(DATA_LENGTH as VARCHAR2(30)) as DATA_LENGTH
							,CAST(DATA_PRECISION as VARCHAR2(30)) as DATA_PRECISION
							,CAST(DATA_SCALE as VARCHAR2(30)) as DATA_SCALE
							,NULLABLE
							,CAST(DEFAULT_LENGTH as VARCHAR2(20)) as DEFAULT_LENGTH
							)
					) order by c.COLUMN_ID
				)
			from SYS.DBA_TAB_COLUMNS c
			where c.OWNER=t.OWNER and c.TABLE_NAME=t.TABLE_NAME
			)
		)
	) as a
from sys.dba_tables t
