select XMLELEMENT( NAME "table"
	,XMLATTRIBUTES(TABSCHEMA,TABNAME,OWNER,OWNERTYPE,TYPE,STATUS,BASE_TABSCHEMA,BASE_TABNAME,ROWTYPESCHEMA,ROWTYPENAME,CREATE_TIME,ALTER_TIME,INVALIDATE_TIME,TBSPACE,INDEX_TBSPACE,LONG_TBSPACE,VOLATILE,COMPRESSION)
	,XMLELEMENT(NAME "columns"
		,(	select XMLAGG(
				XMLELEMENT(NAME "column"
					,XMLATTRIBUTES(COLNO,COLNAME,TYPENAME,LENGTH,SCALE,NULLS)
					) order by c.COLNO
				)
			from syscat.columns c
			where (c.TABSCHEMA,c.TABNAME)=(t.TABSCHEMA,t.TABNAME)
			)
		)
	,(	select XMLELEMENT(NAME "primaryKey"
			,XMLATTRIBUTES( PK_NAME)
					,XMLAGG(XMLELEMENT(NAME "pkColumn"
					,XMLATTRIBUTES(COLumn_NAME as COLNAME,key_SEQ)
					) order by key_SEQ
				)
			,XMLELEMENT(NAME "siblings"
				,(	select XMLAGG(
						XMLELEMENT(NAME "child"
							,XMLATTRIBUTES( s.CONSTNAME,s.OWNER,s.OWNERTYPE,s.REFKEYNAME,s.TABSCHEMA,s.TABNAME,s.COLCOUNT,s.DELETERULE,s.UPDATERULE,s.CREATE_TIME,s.FK_COLNAMES,s.PK_COLNAMES,s.DEFINER)
							) order by CONSTNAME
						)
					from SYSCAT.REFERENCES s
					where (s.REFTABSCHEMA,s.REFTABNAME)=(t.TABSCHEMA,t.TABNAME)
					)
				)
			)
		from sysibm.SQLPRIMARYKEYS pk
		where (pk.TABlE_SCHEM,pk.TABlE_NAME)=(t.TABSCHEMA,t.TABNAME)
		group by PK_NAME
		)
	,XMLELEMENT(NAME "foreignKeys"
		,(	select XMLAGG(
				XMLELEMENT(NAME "parent"
					,XMLATTRIBUTES( fk.CONSTNAME,fk.OWNER,fk.OWNERTYPE,fk.REFKEYNAME,fk.REFTABSCHEMA,fk.REFTABNAME,fk.COLCOUNT,fk.DELETERULE,fk.UPDATERULE,fk.CREATE_TIME,fk.FK_COLNAMES,fk.PK_COLNAMES,fk.DEFINER)
					) order by CONSTNAME
				)
			from SYSCAT.REFERENCES fk
			where (fk.TABSCHEMA,fk.TABNAME)=(t.TABSCHEMA,t.TABNAME)
			)
		)
	,XMLELEMENT(NAME "indices"
		,(	select XMLAGG(
				XMLELEMENT(NAME "index"
					,XMLATTRIBUTES(INDSCHEMA,INDNAME,OWNER,OWNERTYPE,COLNAMES,UNIQUERULE,MADE_UNIQUE,COLCOUNT,UNIQUE_COLCOUNT,INDEXTYPE,ENTRYTYPE,PCTFREE,NLEAF,NLEVELS,FIRSTKEYCARD,FIRST2KEYCARD,FIRST3KEYCARD,FIRST4KEYCARD,FULLKEYCARD,CLUSTERRATIO,CLUSTERFACTOR,SEQUENTIAL_PAGES,DENSITY,USER_DEFINED,SYSTEM_REQUIRED,CREATE_TIME,STATS_TIME,PAGE_FETCH_PAIRS,MINPCTUSED,REVERSE_SCANS,PAGESPLIT,LEVEL2PCTFREE)
					,XMLELEMENT(NAME "indexColumns"
						,(	select XMLAGG(
								XMLELEMENT(NAME "indexColumn"
									,XMLATTRIBUTES(ic.COLNAME,ic.COLSEQ,ic.COLORDER,ic.COLLATIONSCHEMA,ic.COLLATIONNAME)
									) order by ic.COLSEQ
								)
							from SYSCAT.INDEXCOLUSE ic
							where (ic.INDSCHEMA,ic.INDNAME)=(i.INDSCHEMA,i.INDNAME)
							)
						)
					)
				)
			from "SYSCAT"."INDEXES"  i
			where (i.TABSCHEMA,i.TABNAME)=(t.TABSCHEMA,t.TABNAME)
			)
		)
	,XMLELEMENT(NAME "grants"
		,(	select XMLAGG(
					XMLELEMENT(NAME "grant"
					,XMLATTRIBUTES(GRANTOR,GRANTORTYPE,GRANTEE,GRANTEETYPE,CONTROLAUTH,ALTERAUTH,DELETEAUTH,INDEXAUTH,INSERTAUTH,REFAUTH,SELECTAUTH,UPDATEAUTH )
					)
				)
			from "SYSCAT"."TABAUTH"  g
			where (g.TABSCHEMA,g.TABNAME)=(t.TABSCHEMA,t.TABNAME)
			)
		)
	) 
from (select * from syscat.tables t where type='T') AS T
