REVOKE SECURITY LABEL DataAccess.SECRET FROM ROLE custService;
REVOKE SECURITY LABEL DataAccess.TOP_SECRET FROM ROLE Mgr;

REVOKE ALL PRIVILEGES on table ?SCHEMA?.credit_card FROM ROLE Mgr;
REVOKE ALL PRIVILEGES on table ?SCHEMA?.credit_card FROM ROLE custService;

REVOKE ROLE Mgr FROM USER joe;
REVOKE ROLE custService FROM USER bob;




DROP ROLE Mgr;
DROP ROLE custService;

DROP TABLE ?SCHEMA?.credit_card;
DROP SECURITY LABEL DataAccess.SECRET;
DROP SECURITY LABEL DataAccess.TOP_SECRET;
DROP SECURITY POLICY DataAccess;
DROP SECURITY LABEL COMPONENT securityLevel;


