SELECT SUBSTR(WORKLOAD_NAME, 1, 22) AS WL_DEF_NAME,
       WLO_COMPLETED_TOTAL,
       CONCURRENT_WLO_ACT_TOP
FROM TABLE(SYSPROC.WLM_GET_WORKLOAD_STATS_V97(CAST(NULL AS VARCHAR(128)), -2))
     AS WLSTATS;