SELECT SUBSTR(WORKLOADNAME, 1, 20) WL_DEF_NAME,
       SUBSTR(APPL_NAME, 1, 20) APPL_NAME,
       SUBSTR(ACTIVITY_TYPE, 1, 10) ACT_TYPE
FROM SYSIBM.SYSWORKLOADS, ?SCHEMA?.ACTIVITY_DB2ACTIVITIES
WHERE WORKLOADID = WORKLOAD_ID