CREATE WORK ACTION SET db_was FOR DATABASE
   USING WORK CLASS SET  all_class_types
   (WORK ACTION collect_load_wa ON WORK CLASS load_wc
       COLLECT ACTIVITY DATA WITH DETAILS AND VALUES,
    WORK ACTION collect_ddl_wa ON WORK CLASS ddl_wc
       COLLECT ACTIVITY DATA WITH DETAILS AND VALUES,
    WORK ACTION collect_read_wa ON WORK CLASS read_wc
       COLLECT ACTIVITY DATA WITH DETAILS AND VALUES,
    WORK ACTION stop_large_read_wa on WORK CLASS read_wc
       WHEN ESTIMATEDSQLCOST > 10000 STOP EXECUTION )