CREATE WORK ACTION SET sc_was FOR SERVICE CLASS work1_sc 
  USING WORK CLASS SET all_class_types (
   WORK ACTION collect_load_wa ON WORK CLASS load_wc
         COLLECT ACTIVITY DATA ON ALL DATABASE PARTITIONS WITH DETAILS AND VALUES,
   WORK ACTION collect_ddl_wa ON WORK CLASS ddl_wc
         COLLECT ACTIVITY DATA ON ALL DATABASE PARTITIONS WITH DETAILS AND VALUES,
   WORK ACTION collect_read_wa ON WORK CLASS read_wc
         COLLECT ACTIVITY DATA ON ALL DATABASE PARTITIONS WITH DETAILS AND VALUES,
   WORK ACTION map_read_wa on WORK CLASS read_wc
         MAP ACTIVITY TO work1_sc_read)