CREATE WORK CLASS SET all_class_types
    (WORK CLASS read_wc WORK TYPE READ,
     WORK CLASS write_wc WORK TYPE WRITE,
     WORK CLASS ddl_wc WORK TYPE DDL,
     WORK CLASS call_wc WORK TYPE CALL,
     WORK CLASS load_wc WORK TYPE LOAD,
     WORK CLASS all_wc WORK TYPE ALL POSITION LAST);

CREATE WORK ACTION SET work1_was FOR DATABASE
   USING WORK CLASS SET all_class_types
    (WORK ACTION count_read_wa ON WORK CLASS read_wc COUNT ACTIVITY,
    WORK ACTION count_write_wa ON WORK CLASS write_wc COUNT ACTIVITY,
    WORK ACTION count_ddl_wa ON WORK CLASS ddl_wc COUNT ACTIVITY,
    WORK ACTION count_call_wa ON WORK CLASS call_wc COUNT ACTIVITY,
    WORK ACTION count_load_wa ON WORK CLASS load_wc COUNT ACTIVITY,
    WORK ACTION count_all_wa on WORK CLASS all_wc COUNT ACTIVITY)