ALTER SERVICE CLASS SYSDEFAULTSUBCLASS
  UNDER SYSDEFAULTUSERCLASS
  COLLECT AGGREGATE ACTIVITY DATA NONE;

DROP VIEW histograms;
DROP VIEW histogramtimes;
DROP VIEW histogramserviceclasses;
DROP VIEW histogramtypes;

SET EVENT MONITOR DB2STATISTICS STATE 0;

DELETE FROM HISTOGRAMBIN_DB2STATISTICS;
DELETE FROM SCSTATS_DB2STATISTICS;