DROP VIEW HISTOGRAMS#
DROP VIEW HISTOGRAMTIMES#
DROP VIEW HISTOGRAMSERVICECLASSES#
DROP VIEW HISTOGRAMTYPES#
DROP THRESHOLD STOP_LARGE_ACTIVITIES#
DROP THRESHOLD TH_ESTCOST#
DROP THRESHOLD TH_SQLROWS#
DROP WORK ACTION SET WORK1_WAS#
DROP WORK ACTION SET SC_WAS#
DROP WORK ACTION SET DB_WAS#
ALTER WORKLOAD WORK1_WL DISABLE#
DROP WORKLOAD WORK1_WL#
ALTER WORKLOAD WORK2_WL DISABLE#
DROP WORKLOAD WORK2_WL#
ALTER WORKLOAD WORK3_WL DISABLE#
DROP WORKLOAD WORK3_WL#
ALTER WORKLOAD WORKTH_WL DISABLE#
DROP WORKLOAD WORKTH_WL#
ALTER WORKLOAD WORK2_SC DISABLE#
DROP WORKLOAD WORK2_SC#
ALTER SERVICE CLASS WORK1_SC_READ DISABLE#
ALTER SERVICE CLASS WORK1_SC_READ UNDER WORK1_SC DISABLE#
DROP SERVICE CLASS WORK1_SC_READ UNDER WORK1_SC#
DROP SERVICE CLASS WORK1_SC_READ#
DROP WORK CLASS SET ALL_CLASS_TYPES#
SET EVENT MONITOR THREVIO STATE 0#
SET EVENT MONITOR DB2ACTIVITIES STATE 0#
DROP EVENT MONITOR THREVIO#
ALTER SERVICE CLASS WORK2_SC DISABLE#
ALTER SERVICE CLASS WORK1_SC DISABLE#
DROP SERVICE CLASS WORK2_SC#
DROP SERVICE CLASS WORK1_SC#
SET EVENT MONITOR DB2ACTIVITIES STATE 0#
SET EVENT MONITOR DB2STATISTICS STATE 0#
DROP EVENT MONITOR DB2ACTIVITIES#
DROP EVENT MONITOR DB2STATISTICS#
DROP PROCEDURE DROP_WLM#
DROP TYPE TABLE_ARRAY#
DROP TABLE SHOWRESULTS#
CREATE TYPE TABLE_ARRAY AS VARCHAR(128) ARRAY[]#
CREATE TABLE SHOWRESULTS(DROPPED_TABLES VARCHAR(128))#
CREATE PROCEDURE DROP_WLM
  LANGUAGE SQL
BEGIN
  DECLARE TABLES TABLE_ARRAY;
  DECLARE DROPSTMT VARCHAR(128);
  DECLARE I INTEGER;
  
  SET TABLES =
    ARRAY[
      SELECT CAST(
        TRIM(TABSCHEMA) || '.' || TRIM(TABNAME) 
        AS VARCHAR(128)
        )
      FROM SYSCAT.TABLES WHERE
        ( TABNAME LIKE '%DB2STATISTICS%' OR
          TABNAME LIKE '%DB2ACTIVITIES%' OR
          TABNAME LIKE '%THREVIO%')
          AND (TABSCHEMA LIKE '%GRP%' OR
               TABSCHEMA LIKE '%TUT%')
      ];
    
    SET I = 1;
    WHILE I <= CARDINALITY(TABLES) DO
      SET DROPSTMT = 'DROP TABLE ' || TABLES[I];
      INSERT INTO SHOWRESULTS VALUES TABLES[I];
      EXECUTE IMMEDIATE DROPSTMT;
      SET I = I + 1;
    END WHILE;
END#
DROP TYPE TABLE_ARRAY#
CALL DROP_WLM#
SELECT * FROM SHOWRESULTS#