SELECT LASTNAME, SALARY, 
  CASE
    WHEN SALARY <= 20000 THEN 'Poor'
    WHEN SALARY <= 25000 THEN 'Fair'
    WHEN SALARY <= 30000 THEN 'Average'
    WHEN SALARY <= 35000 THEN 'Good'
    WHEN SALARY <= 40000 THEN 'Excellent'
    ELSE 'outstanding'
  END AS COMPENSATION_LEVEL
  FROM EMPLOYEE
  ORDER BY SALARY