MERGE INTO PRODUCTS PR
  USING (SELECT PROD_NO, DESCRIPTION, QUANTITY FROM PRODUCT_TXS) TX
         ON (PR.PROD_NO = TX.PROD_NO)
  WHEN MATCHED THEN 
       UPDATE SET 
              PR.QUANTITY = PR.QUANTITY + TX.QUANTITY
  WHEN NOT MATCHED THEN
       INSERT (PROD_NO, DESCRIPTION, QUANTITY) 
              VALUES (TX.PROD_NO, TX.DESCRIPTION, TX.QUANTITY);

SELECT * FROM PRODUCTS;