DELETE FROM PRODUCT_TXS; 

INSERT INTO PRODUCT_TXS VALUES ('D',10,NULL,NULL);

MERGE INTO PRODUCTS PR
  USING (SELECT TX_TYPE, PROD_NO, DESCRIPTION, QUANTITY FROM PRODUCT_TXS) TX
         ON (PR.PROD_NO = TX.PROD_NO)
  WHEN MATCHED AND TX_TYPE = 'U' THEN 
       UPDATE SET 
              PR.QUANTITY = PR.QUANTITY + TX.QUANTITY
  WHEN MATCHED AND TX_TYPE = 'D' THEN
       DELETE
  WHEN MATCHED AND TX_TYPE = 'I' THEN
       SIGNAL SQLSTATE '70001'
         SET MESSAGE_TEXT = 'Record already exists for an INSERT'
  WHEN NOT MATCHED AND TX_TYPE = 'I' THEN
       INSERT (PROD_NO, DESCRIPTION, QUANTITY) 
              VALUES (TX.PROD_NO, TX.DESCRIPTION, TX.QUANTITY)
  WHEN NOT MATCHED THEN
       SIGNAL SQLSTATE '70002'
         SET MESSAGE_TEXT = 'Record not found for Update or Delete record'
  ELSE IGNORE;