DROP TABLE PRODUCT_TXS;

CREATE TABLE PRODUCT_TXS
  (
  TX_TYPE     CHAR(1)      NOT NULL,
  PROD_NO     INT          NOT NULL,
  DESCRIPTION VARCHAR(20),
  QUANTITY    INT
  )
;

INSERT INTO PRODUCT_TXS
VALUES 
('U',1,NULL,15),('D',3,NULL,NULL),('I',6,'Shoes',5),('I',7,'Belts',10);

MERGE INTO PRODUCTS PR
  USING (SELECT TX_TYPE, PROD_NO, DESCRIPTION, QUANTITY FROM PRODUCT_TXS) TX
         ON (PR.PROD_NO = TX.PROD_NO)
  WHEN MATCHED AND TX_TYPE = 'U' THEN 
       UPDATE SET 
              PR.QUANTITY = PR.QUANTITY + TX.QUANTITY
  WHEN MATCHED AND TX_TYPE = 'D' THEN
       DELETE
  WHEN NOT MATCHED AND TX_TYPE = 'I' THEN
       INSERT (PROD_NO, DESCRIPTION, QUANTITY) 
              VALUES (TX.PROD_NO, TX.DESCRIPTION, TX.QUANTITY);