-- TableSpace partition

DROP TABLE ?SCHEMA?.t1;

CREATE TABLE ?SCHEMA?.t1
  (
  c1 INT NOT NULL,
  c2 INT NOT NULL
  )
PARTITION BY RANGE(c1)
  (
  PARTITION P1 STARTING 1 ENDING 1 IN TBSP1,
  PARTITION P2 STARTING 2 ENDING 2 IN TBSP2
  );
CREATE INDEX i1 on t1(c1);
