GRANT SECADM ON DATABASE TO USER administrator;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ?SCHEMA?.dailysales FROM USER joe;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ?SCHEMA?.dailysales FROM USER bob;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ?SCHEMA?.dailysales FROM USER sue;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ?SCHEMA?.dailysales FROM USER mark;

REVOKE SECURITY LABEL Sec_Policy.EAST FROM USER sam;
REVOKE SECURITY LABEL Sec_Policy.WEST FROM USER nick;
REVOKE SECURITY LABEL Sec_Policy.NORTH FROM USER betcy;
REVOKE SECURITY LABEL Sec_Policy.SOUTH FROM USER bob;
REVOKE SECURITY LABEL Sec_Policy.CENTRAL FROM USER joe;
REVOKE SECURITY LABEL Sec_Policy.COASTAL FROM USER sue;
REVOKE SECURITY LABEL Sec_Policy.SALES_ORGANIZATION FROM USER mark;


DROP TABLE ?SCHEMA?.dailysales;
DROP SECURITY LABEL Sec_Policy.SALES_ORGANIZATION;
DROP SECURITY LABEL Sec_Policy.COASTAL ;
DROP SECURITY LABEL Sec_Policy.CENTRAL;
DROP SECURITY LABEL Sec_Policy.SOUTH;
DROP SECURITY LABEL Sec_Policy.NORTH;
DROP SECURITY LABEL Sec_Policy.EAST;
DROP SECURITY LABEL Sec_Policy.WEST;
DROP SECURITY POLICY Sec_Policy;
DROP SECURITY LABEL COMPONENT Sec_Comp;


