CREATE EVENT MONITOR DB2ACTIVITIES FOR ACTIVITIES WRITE TO TABLE;
CREATE EVENT MONITOR DB2STATISTICS FOR STATISTICS WRITE TO TABLE;

SET EVENT MONITOR DB2ACTIVITIES STATE 1;
SET EVENT MONITOR DB2STATISTICS STATE 1;