CREATE EVENT MONITOR threvio FOR THRESHOLD VIOLATIONS 
  WRITE TO TABLE
  THRESHOLDVIOLATIONS(IN userspace1),  
  CONTROL(IN userspace1);

SET EVENT MONITOR threvio STATE 1;
SET EVENT MONITOR db2activities STATE 1;