SET EVENT MONITOR DB2ACTIVITIES STATE 0#
DROP EVENT MONITOR DB2ACTIVITIES#
DROP PROCEDURE DROP_WLM#
DROP TYPE TABLE_ARRAY#
DROP TABLE SHOWRESULTS#
CREATE TYPE TABLE_ARRAY AS VARCHAR(128) ARRAY[]#
CREATE TABLE SHOWRESULTS(DROPPED_TABLES VARCHAR(128))#
CREATE PROCEDURE DROP_WLM
  LANGUAGE SQL
BEGIN
  DECLARE TABLES TABLE_ARRAY;
  DECLARE DROPSTMT VARCHAR(128);
  DECLARE I INTEGER;
  
  SET TABLES =
    ARRAY[
      SELECT CAST(
        TRIM(TABSCHEMA) || '.' || TRIM(TABNAME) 
        AS VARCHAR(128)
        )
      FROM SYSCAT.TABLES WHERE
        ( TABNAME LIKE '%DB2ACTIVITIES%')
          AND (TABSCHEMA LIKE '%GRP%' OR
               TABSCHEMA LIKE '%TUT%')
      ];
    
    SET I = 1;
    WHILE I <= CARDINALITY(TABLES) DO
      SET DROPSTMT = 'DROP TABLE ' || TABLES[I];
      INSERT INTO SHOWRESULTS VALUES TABLES[I];
      EXECUTE IMMEDIATE DROPSTMT;
      SET I = I + 1;
    END WHILE;
END#
DROP TYPE TABLE_ARRAY#
CALL DROP_WLM#
SELECT * FROM SHOWRESULTS#

CREATE EVENT MONITOR DB2ACTIVITIES FOR ACTIVITIES WRITE TO TABLE#
