SET EVENT MONITOR threvio STATE 0;
SET EVENT MONITOR db2activities STATE 0;

ALTER THRESHOLD th_estcost DISABLE;
DROP THRESHOLD th_estcost;
ALTER THRESHOLD th_sqlrows DISABLE;
DROP THRESHOLD th_sqlrows;

DELETE from ACTIVITY_DB2ACTIVITIES;
DELETE from ACTIVITYSTMT_DB2ACTIVITIES;

DELETE from THRESHOLDVIOLATIONS_THREVIO;

CALL WLM_COLLECT_STATS();