SELECT VARCHAR(A.APPL_NAME, 15) as APPL_NAME,
  	 VARCHAR(A.TPMON_CLIENT_APP, 20) AS CLIENT_APP_NAME,
	 A.ACTIVITY_ID,
	 A.ACTIVITY_TYPE,
	 A.WORKLOAD_ID,
	 T.THRESHOLD_PREDICATE,          
	 A.QUERY_CARD_ESTIMATE,
	 T.THRESHOLD_MAXVALUE,
	 T.TIME_OF_VIOLATION,
	 VARCHAR(AS.STMT_TEXT, 100) AS STMT_TEXT
FROM	THRESHOLDVIOLATIONS_THREVIO AS T,
	 ACTIVITY_DB2ACTIVITIES AS A,
	 ACTIVITYSTMT_DB2ACTIVITIES AS AS       
WHERE	T.APPL_ID = A.APPL_ID AND
	 T.UOW_ID = A.UOW_ID AND
		T.ACTIVITY_ID = A.ACTIVITY_ID AND
		A.APPL_ID = AS.APPL_ID AND
		A.ACTIVITY_ID = AS.ACTIVITY_ID AND
		A.UOW_ID = AS.UOW_ID