DROP TABLE ?SCHEMA?.out_patient_data_PDD1;
DROP TABLE TABLESPACE CommonTBSpace_PDD1;
DROP BUFFERPOOL bp8k_PDD1;

DROP TABLE ?SCHEMA?. out_patient_data_CLOB;
DROP TABLE TABLESPACE CLOBData_PDD2;

DROP TABLE ?SCHEMA?. out_patient_data_PDD2 
DROP TABLE TABLESPACE relData_PDD2;
DROP TABLE TABLESPACE xmlData_PDD2;
DROP BUFFERPOOL bp4k_PDD2;
DROP BUFFERPOOL bp32k_PDD2;


DROP TABLE ?SCHEMA?. out_patient_data_PDD3;
DROP TABLE TABLESPACE CommonTBSpace_PDD3; 
DROP BUFFERPOOL bp8k_PDD3;


