CREATE TABLE STUDENTS
  (SCHOOL_ID      INT NOT NULL,
   PROGRAM_ID     INT NOT NULL,
   STUDENT_NUM    INT NOT NULL,
   STUDENT_ID     INT NOT NULL,
   FIRST_NAME     CHAR(10) NOT NULL,
   LAST_NAME      CHAR(10) NOT NULL,
   GPA            DECIMAL(3,2) NOT NULL)
    
   ORGANIZE BY KEY SEQUENCE
     (STUDENT_ID     STARTING FROM 1 ENDING AT 100)
   DISALLOW OVERFLOW
 ;