CREATE TABLE STUDENTS_NEW
  (SCHOOL_ID      INT NOT NULL,
   CLASS_ID       INT NOT NULL,
   STUDENT_NUM    INT NOT NULL,
   STUDENT_ID     INT NOT NULL,
   FIRST_NAME     CHAR(10) NOT NULL,
   LAST_NAME      CHAR(10) NOT NULL,
   GPA            DECIMAL(3,2) NOT NULL)
    
   ORGANIZE BY KEY SEQUENCE
      (SCHOOL_ID      STARTING FROM 1 ENDING AT 5,
       CLASS_ID       STARTING FROM 1 ENDING AT 10,
       STUDENT_NUM    STARTING FROM 1 ENDING AT 20)
       ALLOW OVERFLOW;