CREATE VIEW TEMP_RESULTS AS (
   SELECT INTEGER(APPLICATION_HANDLE) APPL_HANDLE,
      VARCHAR(CLIENT_APPLNAME, 15) AS APPL_NAME,
      VARCHAR(SYSTEM_AUTH_ID, 20) AS USER_ID
      FROM TABLE
      (WLM_GET_SERVICE_CLASS_WORKLOAD_OCCURRENCES('', '', -2)));

SELECT INTEGER(APPLICATION_HANDLE) AS APPL_HANDLE,
   UOW_ID, ACTIVITY_ID,
   VARCHAR(AGENT_TYPE, 15) AS AGENT_TYPE,
   VARCHAR(AGENT_STATE, 10) AS AGENT_STATE,
   VARCHAR(EVENT_TYPE, 10) AS EVENT_TYPE,
   VARCHAR(EVENT_OBJECT, 10) AS EVENT_OBJ,
   VARCHAR(EVENT_STATE, 10) AS EVENT_STATE
FROM TABLE
   (WLM_GET_SERVICE_CLASS_AGENTS('', '', 
   (SELECT APPL_HANDLE FROM TEMP_RESULTS WHERE APPL_NAME = 'WLM_tut_app2'),
   -2));