CREATE VIEW TE_ACTIVITY AS (
     SELECT T.APPLICATION_HANDLE, 
            T.UOW_ID, T.ACTIVITY_ID, 
            T.ACTIVITY_TYPE, 
            T.LOCAL_START_TIME
     FROM SYSIBMADM.APPLICATIONS A,
          TABLE(SYSPROC.WLM_GET_WORKLOAD_OCCURRENCE_ACTIVITIES
          (CAST(NULL AS BIGINT), -2)) T
     WHERE (A.AGENT_ID = T.APPLICATION_HANDLE) AND
           (A.COORD_NODE_NUM = T.COORD_PARTITION_NUM) AND
           (A.DBPARTITIONNUM = T.DBPARTITIONNUM) AND
           (T.DBPARTITIONNUM = T.COORD_PARTITION_NUM) AND 
           (A.APPL_NAME = 'httpd.exe'));

SELECT * FROM TE_ACTIVITY ORDER BY LOCAL_START_TIME;

CALL WLM_CANCEL_ACTIVITY(
    (SELECT APPLICATION_HANDLE FROM TE_ACTIVITY
        ORDER BY LOCAL_START_TIME FETCH FIRST ROW ONLY),
    (SELECT UOW_ID FROM TE_ACTIVITY
        ORDER BY LOCAL_START_TIME FETCH FIRST ROW ONLY),
    (SELECT ACTIVITY_ID FROM TE_ACTIVITY
        ORDER BY LOCAL_START_TIME FETCH FIRST ROW ONLY));
    
DROP VIEW TE_ACTIVITY;