VALUES
  ('DD/MM/YY',TO_CHAR(CURRENT TIMESTAMP,'DD/MM/YY')),
  ('YYYY-MM-DD',TO_CHAR(CURRENT TIMESTAMP,'YYYY-MM-DD')), 
  ('YYYY.DDD',TO_CHAR(CURRENT TIMESTAMP,'YYYY.DDD')),
  ('YYYYMMDD',TO_CHAR(CURRENT TIMESTAMP,'YYYYMMDD')),
  ('HH.MI',TO_CHAR(CURRENT TIMESTAMP,'HH.MI')),
  ('HH:MM:SS',TO_CHAR(CURRENT TIMESTAMP,'HH:MM:SS'))