CREATE TABLE DB2AUDIT.CHECKING ( TIMESTAMP CHAR(26),
                        CATEGORY CHAR(8),
                        EVENT VARCHAR(32),
                        CORRELATOR INTEGER,
                        STATUS INTEGER,
                        DATABASE CHAR(8),
                        USERID VARCHAR(1024),
                        AUTHID VARCHAR(128),
                        NODENUM SMALLINT,
                        COORDNUM SMALLINT,
                        APPID VARCHAR(255),
                        APPNAME VARCHAR(1024),
                        PKGSCHEMA VARCHAR(128),
                        PKGNAME VARCHAR(128),
                        PKGSECNUM SMALLINT,
                        OBJSCHEMA VARCHAR(128),
                        OBJNAME VARCHAR(128),
                        OBJTYPE VARCHAR(32),
                        ACCESSAPP CHAR(18),
                        ACCESSATT CHAR(18),
                        PKGVER VARCHAR(64),
                        CHKAUTHID VARCHAR(128),
                        LCLTRANSID VARCHAR(10) FOR BIT DATA,
                        GLBLTRANSID VARCHAR(30) FOR BIT DATA,
                        CLNTUSERID VARCHAR(255),
                        CLNTWRKSTNAME VARCHAR(255),
                        CLNTAPPNAME VARCHAR(255),
                        CLNTACCSTRING VARCHAR(255),
                        TRSTCTXNAME VARCHAR(255),
                        CONTRSTTYPE INTEGER,
                        ROLEINHERITED VARCHAR(128));







CREATE TABLE DB2AUDIT.EXECUTE ( TIMESTAMP CHAR(26),
                       CATEGORY CHAR(8),
                       EVENT VARCHAR(32),
                       CORRELATOR INTEGER,
                       STATUS INTEGER,
                       DATABASE CHAR(8),
                       USERID VARCHAR(1024),
                       AUTHID VARCHAR(128),
                       SESSNAUTHID VARCHAR(128),
                       NODENUM SMALLINT,
                       COORDNUM SMALLINT,
                       APPID VARCHAR(255),
                       APPNAME VARCHAR(1024),
                       CLNTUSERID VARCHAR(255),
                       CLNTWRKSTNAME VARCHAR(255),
                       CLNTAPPNAME VARCHAR(255),
                       CLNTACCSTRING VARCHAR(255),
                       TRSTCTXNAME VARCHAR(255),
                       CONTRSTTYPE INTEGER,
                       ROLEINHERITED VARCHAR(128),
                       PKGSCHEMA VARCHAR(128),
                       PKGNAME VARCHAR(128),
                       PKGSECNUM SMALLINT,
                       PKGVER VARCHAR(64),
                       LCLTRANSID VARCHAR(10) FOR BIT DATA,
                       GLBLTRANSID VARCHAR(30) FOR BIT DATA,
                       UOWID BIGINT,
                       ACTIVITYID BIGINT,
                       STMTINVOCID BIGINT,
                       STMTNESTLVL BIGINT,
                       ACTIVITYTYPE VARCHAR(32),
                       STMTTEXT CLOB(8M),
                       STMTISOLATIONLVL CHAR(8),
                       COMPENVDESC BLOB(8K),
                       ROWSMODIFIED INTEGER,
                       ROWSRETURNED BIGINT,
                       SAVEPOINTID BIGINT,
                       STMTVALINDEX INTEGER,
                       STMTVALTYPE CHAR(16),
                       STMTVALDATA CLOB(128K));
