-- View all the audited data in the audit tables.
SELECT * FROM DB2AUDIT.AUDIT;
SELECT * FROM DB2AUDIT.CHECKING;
SELECT * FROM DB2AUDIT.OBJMAINT;
SELECT * FROM DB2AUDIT.SECMAINT;
SELECT * FROM DB2AUDIT.EXECUTE;