create table ?SCHEMA?.accounts_third (
    name char(10),
    acctno smallint not null 
           generated by default as
           identity(start with 100, increment by 10))
    ;
    
insert into ?SCHEMA?.accounts_third(name,acctno) values
('George',24),
('Paul',default),
('Kevin',36),
('Jim',default),
('Bert',default),
('Glen',46);

select * from ?SCHEMA?.accounts_third;