CALL WLM_CANCEL_ACTIVITY(
	(SELECT APPLICATION_HANDLE FROM LONGQUERY_ACTIVITY),
	(SELECT UOW_ID FROM LONGQUERY_ACTIVITY),
	(SELECT ACTIVITY_ID FROM LONGQUERY_ACTIVITY)
);
    
DROP VIEW LONGQUERY_ACTIVITY;