SELECT T.APPLICATION_HANDLE, T.UOW_ID, T.ACTIVITY_ID, T.ACTIVITY_TYPE
FROM SYSIBMADM.APPLICATIONS A,
     TABLE(WLM_GET_WORKLOAD_OCCURRENCE_ACTIVITIES_V97
          (CAST(NULL AS BIGINT), -2)) T
WHERE (A.AGENT_ID = T.APPLICATION_HANDLE) AND
          (A.COORD_NODE_NUM = T.COORD_PARTITION_NUM) AND
          (A.DBPARTITIONNUM = T.DBPARTITIONNUM) AND
          (T.DBPARTITIONNUM = T.COORD_PARTITION_NUM) AND
          (A.TPMON_CLIENT_APP = 'WLM_tutorial_longquery')