SELECT VARCHAR(A.APPL_NAME, 15) as APPL_NAME,
     VARCHAR(A.TPMON_CLIENT_APP, 20) AS CLIENT_APP_NAME,
     VARCHAR(A.APPL_ID, 30) as APPL_ID,
     A.ACTIVITY_ID,
     A.UOW_ID,
     A.PARTIAL_RECORD,
     A.TIME_STARTED,
     A.TIME_COMPLETED,
     VARCHAR(S.STMT_TEXT, 300) AS STMT_TEXT
FROM ACTIVITY_DB2ACTIVITIES AS A,
     ACTIVITYSTMT_DB2ACTIVITIES AS S
WHERE A.APPL_ID = S.APPL_ID AND
     A.ACTIVITY_ID = S.ACTIVITY_ID AND
     A.UOW_ID = S.UOW_ID